export const data = [
  {
    name: 'Agua Mineral',
    description: 'Botella de agua mineral de 500ml',
    price: 150.0,
    category: 'Bebidas',
    initialStock: 100,
    minStock: 10,
    img: 'agua_mineral.jpg',
  },
  {
    name: 'Café Expreso',
    description: 'Café expreso recién hecho',
    price: 250.0,
    category: 'Bebidas',
    initialStock: 80,
    minStock: 5,
    img: 'cafe_expresso.jpg',
  },
  {
    name: 'Sándwich de Jamón y Queso',
    description: 'Pan, jamón, queso y vegetales frescos',
    price: 1200.0,
    category: 'Comidas',
    initialStock: 50,
    minStock: 5,
    img: 'sandwich_jamon_queso.jpg',
  },
  {
    name: 'Ensalada César',
    description: 'Lechuga, pollo, croutons y aderezo César',
    price: 1500.0,
    category: 'Comidas',
    initialStock: 40,
    minStock: 5,
    img: 'ensalada_cesar.jpg',
  },
  {
    name: 'Brownie con Helado',
    description: 'Brownie de chocolate con helado de vainilla',
    price: 800.0,
    category: 'Postres',
    initialStock: 30,
    minStock: 3,
    img: 'brownie_helado.jpg',
  },
  {
    name: 'Cerveza Artesanal',
    description: 'Cerveza local de 330ml',
    price: 400.0,
    category: 'Bebidas',
    initialStock: 60,
    minStock: 5,
    img: 'cerveza_artesanal.jpg',
  },
  {
    name: 'Galletas Saladas',
    description: 'Snack de galletas saladas surtidas',
    price: 350.0,
    category: 'Snacks',
    initialStock: 50,
    minStock: 5,
    img: 'galletas_saladas.jpg',
  },
  {
    name: 'Pizza Personal',
    description: 'Pizza individual con queso y tomate',
    price: 1800.0,
    category: 'Comidas',
    initialStock: 25,
    minStock: 3,
    img: 'pizza_personal.jpg',
  },
];
